export const API_CONFIG = {
  baseURL: import.meta.env.VITE_API_URL || 'http://localhost:3010',
  timeout: 30000,
};

export const ENDPOINTS = {
  // Auth
  auth: {
    login: '/auth/login',
    register: '/auth/register',
    logout: '/auth/logout',
    refresh: '/auth/refresh',
    me: '/users/me',
    google: '/auth/google',
    apple: '/auth/apple',
    forgotPassword: '/auth/forgot-password',
    resetPassword: '/auth/reset-password',
    verifyEmail: '/auth/verify-email',
    resendVerification: '/auth/resend-verification',
    changePassword: '/auth/change-password',
  },
  // Users
  users: {
    profile: '/users/me',
    preferences: '/users/preferences',
    stats: '/users/me/stats',
    gamification: '/users/me/gamification',
    addXp: '/users/me/xp',
  },
  // Analytics
  analytics: {
    me: '/analytics/me',
    activity: '/analytics/me/activity',
    performance: '/analytics/me/performance',
    track: '/analytics/track',
  },
  // Study Sets
  studySets: {
    list: '/study-sets',
    create: '/study-sets',
    get: (id: string) => `/study-sets/${id}`,
    update: (id: string) => `/study-sets/${id}`,
    delete: (id: string) => `/study-sets/${id}`,
    studySchedule: (id: string) => `/study-sets/${id}/study-schedule`,
  },
  // Documents
  documents: {
    list: '/documents',
    upload: '/documents',
    get: (id: string) => `/documents/${id}`,
    delete: (id: string) => `/documents/${id}`,
    byStudySet: (studySetId: string) => `/documents/study-set/${studySetId}`,
    downloadUrl: (id: string) => `/documents/${id}/download-url`,
  },
  // Flashcards
  flashcards: {
    list: (studySetId: string) => `/study-sets/${studySetId}/flashcards`,
    create: (studySetId: string) => `/study-sets/${studySetId}/flashcards`,
    update: (id: string) => `/flashcards/${id}`,
    delete: (id: string) => `/flashcards/${id}`,
    review: (id: string) => `/flashcards/${id}/review`,
  },
  // Knowledge Base
  knowledgeBase: {
    list: '/knowledge-bases',
    create: '/knowledge-bases',
    get: (id: string) => `/knowledge-bases/${id}`,
    delete: (id: string) => `/knowledge-bases/${id}`,
    search: (id: string) => `/knowledge-bases/${id}/search`,
    addDocument: (id: string) => `/knowledge-bases/${id}/documents`,
  },
  // Chat
  chat: {
    conversations: '/chat/conversations',
    create: '/chat/conversations',
    get: (id: string) => `/chat/conversations/${id}`,
    messages: (id: string) => `/chat/conversations/${id}/messages`,
    send: (id: string) => `/chat/conversations/${id}/messages`,
    stream: (id: string) => `/chat/conversations/${id}/messages/stream`,
    update: (id: string) => `/chat/conversations/${id}`,
    delete: (id: string) => `/chat/conversations/${id}`,
  },
  // Quiz
  quiz: {
    list: '/quizzes',
    create: '/quizzes',
    get: (id: string) => `/quizzes/${id}`,
    generate: '/quizzes/generate',
    questions: (id: string) => `/quizzes/${id}/questions`,
    attempt: (id: string) => `/quizzes/${id}/attempts`,
    attemptDetail: (attemptId: string) => `/quizzes/attempts/${attemptId}`,
    byStudySet: (studySetId: string) => `/quizzes/study-set/${studySetId}`,
    submit: (id: string, attemptId: string) =>
      `/quizzes/${id}/attempts/${attemptId}/submit`,
  },
  // Exam Clone
  examClone: {
    list: '/exam-clones',
    upload: (id: string) => `/exam-clones/${id}/upload`,
    get: (id: string) => `/exam-clones/${id}`,
    generate: (id: string) => `/exam-clones/${id}/generate`,
    questions: (id: string) => `/exam-clones/${id}/questions`,
    // Analytics & Practice
    analytics: (id: string) => `/exam-clones/${id}/analytics`,
    submitAttempt: (id: string) => `/exam-clones/${id}/attempt`,
    explanation: (questionId: string) => `/exam-clones/questions/${questionId}/explanation`,
    reviewQueue: '/exam-clones/review-queue',
    completeReview: (questionId: string) => `/exam-clones/review/${questionId}`,
    adaptiveQuestions: (id: string) => `/exam-clones/${id}/adaptive-questions`,
    templates: '/exam-clones/templates/list',
    generateFromTemplate: (id: string) => `/exam-clones/${id}/generate-from-template`,
    // Bookmarks
    bookmarks: '/exam-clones/bookmarks',
    bookmark: (questionId: string) => `/exam-clones/bookmarks/${questionId}`,
    // Badges
    badges: '/exam-clones/badges',
    userBadges: '/exam-clones/badges/user',
    // Leaderboard
    leaderboard: '/exam-clones/leaderboard',
  },
  // Problem Solver
  problemSolver: {
    create: '/problem-solver',
    list: '/problem-solver',
    get: (id: string) => `/problem-solver/${id}`,
    solve: (id: string) => `/problem-solver/${id}/solve`,
    solveStream: (id: string) => `/problem-solver/${id}/solve/stream`,
    delete: (id: string) => `/problem-solver/${id}`,
    similar: (id: string) => `/problem-solver/${id}/similar`,
    chat: (id: string) => `/problem-solver/${id}/chat`,
    chatMessages: (id: string) => `/problem-solver/${id}/chat/messages`,
    // New features
    bookmark: (id: string) => `/problem-solver/${id}/bookmark`,
    bookmarkStatus: (id: string) => `/problem-solver/${id}/bookmark/status`,
    bookmarks: '/problem-solver/bookmarks',
    hint: (id: string) => `/problem-solver/${id}/hint`,
    hintReset: (id: string) => `/problem-solver/${id}/hint/reset`,
    alternativeMethods: (id: string) => `/problem-solver/${id}/alternative-methods`,
    practiceQuiz: (id: string) => `/problem-solver/${id}/practice-quiz`,
    quizAnswer: (questionId: string) => `/problem-solver/quiz/${questionId}/answer`,
    explain: (id: string) => `/problem-solver/${id}/explain`,
    conceptMap: (id: string) => `/problem-solver/${id}/concept-map`,
    formulaCards: (id: string) => `/problem-solver/${id}/formula-cards`,
    graph: (id: string) => `/problem-solver/${id}/graph`,
    narration: (id: string) => `/problem-solver/${id}/narration`,
    batchExtract: '/problem-solver/batch/extract',
  },

  // Teach Back
  teachBack: {
    list: '/teach-back',
    create: '/teach-back',
    createFromStudySet: '/teach-back/from-study-set',
    get: (id: string) => `/teach-back/${id}`,
    essentials: (id: string) => `/teach-back/${id}/essentials`,
    submit: (id: string) => `/teach-back/${id}/submit`,
    evaluate: (id: string) => `/teach-back/${id}/evaluate`,
    challengeStart: (id: string) => `/teach-back/${id}/challenge/start`,
    challengeRespond: (id: string) => `/teach-back/${id}/challenge/respond`,
    delete: (id: string) => `/teach-back/${id}`,
  },
  // Research
  research: {
    list: '/research',
    create: '/research',
    get: (id: string) => `/research/${id}`,
    start: (id: string) => `/research/${id}/start`,
    delete: (id: string) => `/research/${id}`,
  },
  // Code Sandbox
  codeSandbox: {
    execute: '/code-sandbox/execute',
    sessions: '/code-sandbox/sessions',
  },
  // Content Import
  content: {
    extract: '/content/extract',
    extractYoutube: '/content/extract-youtube',
    extractWebsite: '/content/extract-website',
    extractAudio: '/content/extract-audio',
    extractHandwriting: '/content/extract-handwriting',
  },
  // Content Sources
  contentSources: {
    create: '/content-sources',
    byStudySet: (studySetId: string) => `/content-sources/study-set/${studySetId}`,
    delete: (id: string) => `/content-sources/${id}`,
  },
  // AI
  ai: {
    generateFlashcards: '/ai/generate-flashcards',
    generateQuiz: '/ai/generate-quiz',
    summarize: '/ai/summarize',
    assistCard: '/ai/assist-card',
    adjustCards: '/ai/adjust-cards',
    generateSlides: '/ai/generate-slides',
  },
  // Learning Paths
  learningPaths: {
    list: '/learning-paths',
    create: '/learning-paths',
    generate: '/learning-paths/generate',
    get: (id: string) => `/learning-paths/${id}`,
    completeStep: (id: string, stepId: string) => `/learning-paths/${id}/steps/${stepId}/complete`,
    fromProgramme: '/learning-paths/from-programme',
    delete: (id: string) => `/learning-paths/${id}`,
  },
  // Subscription
  subscription: {
    current: '/subscription',
    plans: '/subscription/plans',
    checkout: '/subscription/checkout',
    portal: '/subscription/portal',
    cancel: '/subscription/cancel',
    usage: '/subscription/usage',
    verifySession: '/subscription/verify-session',
  },
  // Notifications
  notifications: {
    list: '/notifications',
    markAsRead: (id: string) => `/notifications/${id}/read`,
    markAllAsRead: '/notifications/read-all',
    delete: (id: string) => `/notifications/${id}`,
    deleteAll: '/notifications',
    preferences: '/notifications/preferences',
    webPushPublicKey: '/notifications/web-push/public-key',
    webPushSubscribe: '/notifications/web-push/subscribe',
    webPushUnsubscribe: '/notifications/web-push/unsubscribe',
  },
  // Blog
  blog: {
    list: '/blog',
    categories: '/blog/categories',
    get: (slug: string) => `/blog/${slug}`,
    related: (slug: string) => `/blog/${slug}/related`,
    rating: (postId: string) => `/blog/${postId}/rating`,
    rate: (postId: string) => `/blog/${postId}/rating`,
    comments: (postId: string) => `/blog/${postId}/comments`,
    addComment: (postId: string) => `/blog/${postId}/comments`,
    deleteComment: (commentId: string) => `/blog/comments/${commentId}`,
  },
  // Notes
  notes: {
    list: (studySetId: string) => `/study-sets/${studySetId}/notes`,
    create: (studySetId: string) => `/study-sets/${studySetId}/notes`,
    get: (id: string) => `/notes/${id}`,
    update: (id: string) => `/notes/${id}`,
    delete: (id: string) => `/notes/${id}`,
    togglePin: (id: string) => `/notes/${id}/pin`,
  },
  // Study Tasks (Planner)
  tasks: {
    list: '/tasks',
    today: '/tasks/today',
    create: '/tasks',
    get: (id: string) => `/tasks/${id}`,
    update: (id: string) => `/tasks/${id}`,
    complete: (id: string) => `/tasks/${id}/complete`,
    reopen: (id: string) => `/tasks/${id}/reopen`,
    delete: (id: string) => `/tasks/${id}`,
  },
  // Academics (Phase 2 Study RPG Core)
  academics: {
    structure: '/academics/structure',
    profile: '/academics/profile',
    subjects: '/academics/subjects',
    subject: (id: string) => `/academics/subjects/${id}`,
    chapters: (subjectId: string) => `/academics/subjects/${subjectId}/chapters`,
    chapter: (id: string) => `/academics/chapters/${id}`,
    topics: (chapterId: string) => `/academics/chapters/${chapterId}/topics`,
    topic: (id: string) => `/academics/topics/${id}`,
    exams: '/academics/exams',
    exam: (id: string) => `/academics/exams/${id}`,
    portions: (examId: string) => `/academics/exams/${examId}/portions`,
    portion: (examId: string, portionId: string) =>
      `/academics/exams/${examId}/portions/${portionId}`,
  },
  // Focus Sessions (Study Tools)
  focusSessions: {
    list: '/focus-sessions',
    create: '/focus-sessions',
    today: '/focus-sessions/today',
    wellbeing: '/focus-sessions/wellbeing',
    pause: (id: string) => `/focus-sessions/${id}/pause`,
    resume: (id: string) => `/focus-sessions/${id}/resume`,
    complete: (id: string) => `/focus-sessions/${id}/complete`,
    update: (id: string) => `/focus-sessions/${id}`,
    delete: (id: string) => `/focus-sessions/${id}`,
  },
  // Mistake Notebook
  mistakes: {
    list: '/mistakes',
    create: '/mistakes',
    resolve: (id: string) => `/mistakes/${id}/resolve`,
    reopen: (id: string) => `/mistakes/${id}/reopen`,
    update: (id: string) => `/mistakes/${id}`,
    delete: (id: string) => `/mistakes/${id}`,
  },
  // Puzzles
  puzzles: {
    subjects: '/puzzles/subjects',
    attempts: '/puzzles/attempts',
    next: '/puzzles/next',
    list: '/puzzles',
    create: '/puzzles',
    submit: (id: string) => `/puzzles/${id}/submit`,
    update: (id: string) => `/puzzles/${id}`,
    delete: (id: string) => `/puzzles/${id}`,
  },
  // Exam Periods / Exam Centre
  examPeriods: {
    list: '/exam-periods',
    nearest: '/exam-periods/nearest-exam',
    get: (id: string) => `/exam-periods/${id}`,
    create: '/exam-periods',
    update: (id: string) => `/exam-periods/${id}`,
    attach: (id: string) => `/exam-periods/${id}/exams`,
    results: '/exam-periods/results/all',
    result: (examId: string) => `/exam-periods/exams/${examId}/results`,
    delete: (id: string) => `/exam-periods/${id}`,
  },
  // Dashboard
  dashboard: {
    summary: '/dashboard/summary',
    preferences: '/dashboard/preferences',
  },
  // Study RPG
  rpg: {
    profile: '/rpg/profile',
    ledger: '/rpg/ledger',
    cards: '/rpg/cards',
    collection: '/rpg/collection',
    decks: '/rpg/decks',
    deck: (id: string) => `/rpg/decks/${id}`,
    equipDeck: (id: string) => `/rpg/decks/${id}/equip`,
    battles: '/rpg/battles',
    battleHistory: '/rpg/battles/history',
    battle: (id: string) => `/rpg/battles/${id}`,
    battleAction: (id: string) => `/rpg/battles/${id}/action`,
    battleQuiz: (id: string) => `/rpg/battles/${id}/quiz`,
    battleChallenge: (id: string) => `/rpg/battles/${id}/challenge`,
    battleForfeit: (id: string) => `/rpg/battles/${id}/forfeit`,
    pvpDuels: '/rpg/pvp/duels',
    pvpDuel: (id: string) => `/rpg/pvp/duels/${id}`,
    pvpDuelBattle: (id: string) => `/rpg/pvp/duels/${id}/battle`,
    pvpLeaderboard: '/rpg/pvp/leaderboard',
  },
  // Study RPG Integrity (spec 014 — campfire metacognitive loop)
  studyIntegrity: {
    campfireStatus: '/study-integrity/campfire/status',
    campfireStart: '/study-integrity/campfire',
    campfireAnswer: (id: string) => `/study-integrity/campfire/${id}/answer`,
    campfireSkip: (id: string) => `/study-integrity/campfire/${id}/skip`,
  },
  // PDF Phase 6 — Economy
  economy: {
    marketplace: '/economy/marketplace',
    listings: '/economy/marketplace/listings',
    listing: (id: string) => `/economy/marketplace/listings/${id}`,
    buyListing: (id: string) => `/economy/marketplace/listings/${id}/buy`,
    offers: '/economy/marketplace/offers',
    makeOffer: (id: string) => `/economy/marketplace/listings/${id}/offers`,
    acceptOffer: (id: string) => `/economy/marketplace/offers/${id}/accept`,
    declineOffer: (id: string) => `/economy/marketplace/offers/${id}/decline`,
    cancelOffer: (id: string) => `/economy/marketplace/offers/${id}/cancel`,
    cards: '/economy/cards',
    moveCard: (id: string) => `/economy/cards/${id}/move`,
    scrapeCard: (id: string) => `/economy/cards/${id}/scrape`,
    burnCard: (id: string) => `/economy/cards/${id}/burn`,
    burnStatus: (id: string) => `/economy/cards/${id}/burn-status`,
    supply: '/economy/supply',
    priceHistory: (cardKey: string) => `/economy/supply/${cardKey}/history`,
    adminReconcile: '/economy/admin/reconcile',
    adminProcessInstalments: '/economy/admin/process-burn-instalments',
  },
  // Phase 6 — Study Community
  admin: {
    users: '/admin/users',
    createUser: '/admin/users',
    updateUser: (id: string) => `/admin/users/${id}/update`,
    resetPassword: (id: string) => `/admin/users/${id}/reset-password`,
    auditLogs: '/admin/audit-logs',
    auditExport: '/admin/audit-logs/export',
    auditRetention: '/admin/audit-logs/retention',
    auditPurge: '/admin/audit-logs/purge',
    status: '/admin/status',
  },
  programmes: {
    list: '/programmes',
    suggest: '/programmes',
    templates: '/programmes/templates',
    template: (id: string) => `/programmes/templates/${id}`,
    suggestFromTemplate: '/programmes/suggest-from-template',
    reviewQueue: '/programmes/review-queue',
    batchReview: '/programmes/batch-review',
    get: (id: string) => `/programmes/${id}`,
    join: (id: string) => `/programmes/${id}/join`,
    leave: (id: string) => `/programmes/${id}/leave`,
    review: (id: string) => `/programmes/${id}/review`,
    archive: (id: string) => `/programmes/${id}/archive`,
  },
  factions: {
    list: '/factions',
    mine: '/factions/mine',
    leaderboard: '/factions/leaderboard',
    helpPledges: '/factions/help-pledges',
    autoAssign: '/factions/auto-assign',
    vote: (id: string) => `/factions/${id}/vote`,
    members: (id: string) => `/factions/${id}/members`,
    election: (id: string) => `/factions/${id}/election`,
    help: (id: string) => `/factions/${id}/help`,
    promoteLeaders: (id: string) => `/factions/${id}/promote-leaders`,
    settle: '/factions/settle',
  },
  social: {
    searchUsers: '/social/users/search',
    friends: '/social/friends',
    conversations: '/social/conversations',
    request: '/social/friends/request',
    accept: (id: string) => `/social/friends/${id}/accept`,
    decline: (id: string) => `/social/friends/${id}/decline`,
    block: '/social/friends/block',
    messages: (friendId: string) => `/social/messages/${friendId}`,
    unread: '/social/unread',
  },
  adminNotes: {
    list: '/admin-notes',
    create: '/admin-notes',
    get: (id: string) => `/admin-notes/${id}`,
    remove: (id: string) => `/admin-notes/${id}`,
    syllabus: '/admin-notes/syllabus',
    syllabusItem: (id: string) => `/admin-notes/syllabus/${id}`,
  },
  rpgParty: {
    examBosses: '/rpg/exam-bosses',
    mine: '/rpg/parties/mine',
    create: '/rpg/parties',
    get: (id: string) => `/rpg/parties/${id}`,
    invite: (id: string) => `/rpg/parties/${id}/invite`,
    leave: (id: string) => `/rpg/parties/${id}/leave`,
    startBattle: (id: string) => `/rpg/parties/${id}/battles`,
    battles: (id: string) => `/rpg/parties/${id}/battles`,
    battle: (id: string) => `/rpg/party-battles/${id}`,
    battleAction: (id: string) => `/rpg/party-battles/${id}/action`,
    battleForfeit: (id: string) => `/rpg/party-battles/${id}/forfeit`,
  },
  // PDF Phase 7 — Study Events
  events: {
    current: '/events/current',
    list: '/events',
    get: (slug: string) => `/events/${slug}`,
    lootBoxOdds: '/events/loot-box-odds',
    quests: '/events/current/quests',
    items: '/events/current/items',
    chooseTrack: '/events/current/study-pass/track',
    claimLevel: '/events/current/study-pass/claim',
    claimQuest: (id: string) => `/events/current/quests/${id}/claim`,
    transferSigil: '/events/current/sigils/transfer',
    myAbstracted: '/events/abstracted/my',
    unabstract: '/events/abstracted/unabstract',
    limbo: '/events/abstracted/limbo',
    extinctionTargets: (slug: string) => `/events/${slug}/extinction/targets`,
    seedTargets: (slug: string) => `/events/${slug}/extinction/targets`,
    milestones: (slug: string) => `/events/${slug}/milestones`,
    claimMilestone: (slug: string, id: string) => `/events/${slug}/milestones/${id}/claim`,
    create: '/events',
    activate: (id: string) => `/events/${id}/activate`,
  },
};
