#!/bin/bash
# Study RPG — First-run bootstrap
# Idempotent: safe to run multiple times. Waits for services, runs migrations,
# pulls Ollama models, creates buckets, generates VAPID keys, seeds data.
#
# Usage:
#   docker compose up -d
#   sh scripts/bootstrap.sh
#
# Or just:
#   sh scripts/bootstrap.sh   (starts everything if not running)

set -euo pipefail

GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

info()  { echo -e "${BLUE}[INFO]${NC}  $1"; }
ok()    { echo -e "${GREEN}[OK]${NC}    $1"; }
warn()  { echo -e "${YELLOW}[WARN]${NC}  $1"; }
fail()  { echo -e "${RED}[FAIL]${NC}  $1"; exit 1; }

# ── 1. Check Docker ──────────────────────────────────────────────
if ! docker info > /dev/null 2>&1; then
  fail "Docker is not running. Start Docker Desktop or Docker Engine first."
fi
ok "Docker is running"

# ── 2. Create .env if missing ────────────────────────────────────
if [ ! -f .env ]; then
  warn "No .env found — creating from docker-compose defaults"
  cat > .env <<'ENVEOF'
# Study RPG — Docker Compose Environment (auto-generated by bootstrap.sh)
POSTGRES_USER=postgres
POSTGRES_PASSWORD=postgres
POSTGRES_DB=studyrpg
POSTGRES_PORT=5432
REDIS_PORT=6379
QDRANT_PORT=6333
QDRANT_GRPC_PORT=6334
CLICKHOUSE_PORT=8123
CLICKHOUSE_DATABASE=studyrpg_analytics
CLICKHOUSE_USER=default
CLICKHOUSE_PASSWORD=
OLLAMA_PORT=11434
MINIO_ROOT_USER=minioadmin
MINIO_ROOT_PASSWORD=minioadmin
MINIO_API_PORT=9000
MINIO_CONSOLE_PORT=9001
MAILPIT_SMTP_PORT=1025
MAILPIT_UI_PORT=8025
SEARXNG_PORT=8888
SEARXNG_SECRET=change-me-to-a-random-string
CODE_RUNNER_PORT=9000
BACKEND_PORT=3010
FRONTEND_PORT=8080
JWT_ACCESS_SECRET=dev-access-secret-change-in-production-min-32-chars
JWT_REFRESH_SECRET=dev-refresh-secret-change-in-production-min-32-chars
ENVEOF
  ok "Created .env with local-first defaults"
fi

# ── 3. Start all services ───────────────────────────────────────
info "Starting all services (this may take a few minutes on first run)..."
docker compose up -d

# ── 4. Wait for PostgreSQL ──────────────────────────────────────
info "Waiting for PostgreSQL..."
timeout=120
counter=0
until docker compose exec -T postgres pg_isready -U postgres > /dev/null 2>&1; do
  if [ "$counter" -ge "$timeout" ]; then
    fail "PostgreSQL did not become ready within ${timeout}s"
  fi
  sleep 2
  counter=$((counter + 2))
done
ok "PostgreSQL is ready"

# ── 5. Wait for Redis ───────────────────────────────────────────
info "Waiting for Redis..."
timeout=30
counter=0
until docker compose exec -T redis redis-cli ping > /dev/null 2>&1; do
  if [ "$counter" -ge "$timeout" ]; then
    warn "Redis not ready — continuing anyway"
    break
  fi
  sleep 2
  counter=$((counter + 2))
done
ok "Redis is ready"

# ── 6. Wait for MinIO ──────────────────────────────────────────
info "Waiting for MinIO..."
timeout=60
counter=0
until docker compose exec -T minio mc alias set local http://localhost:9000 minioadmin minioadmin > /dev/null 2>&1; do
  if [ "$counter" -ge "$timeout" ]; then
    warn "MinIO not ready — uploads may fail"
    break
  fi
  sleep 2
  counter=$((counter + 2))
done
if [ "$counter" -lt "$timeout" ]; then
  # Create upload bucket (idempotent)
  docker compose exec -T minio mc mb --ignore-existing local/studyrpg-uploads > /dev/null 2>&1 || true
  ok "MinIO is ready and bucket created"
fi

# ── 7. Wait for Ollama ─────────────────────────────────────────
info "Waiting for Ollama..."
timeout=60
counter=0
until docker compose exec -T ollama ollama list > /dev/null 2>&1; do
  if [ "$counter" -ge "$timeout" ]; then
    warn "Ollama not ready — AI features may not work until models are pulled"
    break
  fi
  sleep 2
  counter=$((counter + 2))
done

# ── 8. Pull Ollama models ──────────────────────────────────────
if [ "$counter" -lt "$timeout" ]; then
  info "Pulling Ollama models (qwen2.5:7b + nomic-embed-text)... this takes a few minutes"
  docker compose exec -T ollama ollama pull qwen2.5:7b-instruct &
  docker compose exec -T ollama ollama pull nomic-embed-text &
  wait
  ok "Ollama models pulled"
fi

# ── 9. Wait for backend ────────────────────────────────────────
info "Waiting for backend API..."
timeout=120
counter=0
until docker compose exec -T backend curl -sf http://localhost:3010/health > /dev/null 2>&1; do
  if [ "$counter" -ge "$timeout" ]; then
    warn "Backend not responding — check logs with: docker compose logs backend"
    break
  fi
  sleep 3
  counter=$((counter + 3))
done
if [ "$counter" -lt "$timeout" ]; then
  ok "Backend API is healthy"
fi

# ── 10. Run migrations ─────────────────────────────────────────
info "Running database migrations..."
docker compose exec -T backend node scripts/migrate.js 2>&1 | tail -5 || warn "Migrations may have already been applied"
ok "Migrations complete"

# ── 11. Summary ────────────────────────────────────────────────
echo ""
echo -e "${GREEN}═══════════════════════════════════════════════════════════${NC}"
echo -e "${GREEN}  Study RPG is ready!${NC}"
echo -e "${GREEN}═══════════════════════════════════════════════════════════${NC}"
echo ""
echo "  Frontend:   http://localhost:${FRONTEND_PORT:-8080}"
echo "  Backend:    http://localhost:${BACKEND_PORT:-3010}"
echo "  Mail UI:    http://localhost:${MAILPIT_UI_PORT:-8025}"
echo "  MinIO:      http://localhost:${MINIO_CONSOLE_PORT:-9001}"
echo "  Ollama:     http://localhost:${OLLAMA_PORT:-11434}"
echo "  SearXNG:    http://localhost:${SEARXNG_PORT:-8888}"
echo ""
echo "  Login: register a new account at the frontend URL"
echo ""
echo "  Optional upgrades (add keys to .env):"
echo "    OPENROUTER_API_KEY  — better AI models (Claude, GPT-4)"
echo "    TAVILY_API_KEY      — commercial web search"
echo "    AWS_ACCESS_KEY_ID   — production email via SES"
echo ""
